# Generated by Django 4.2.1 on 2023-05-07 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='weather_type',
            field=models.CharField(blank=True, choices=[('rainy', 'Rainy'), ('storm', 'Storm'), ('sunny', 'Sunny'), ('cloudy', 'Cloudy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(60.0)]),
        ),
    ]
