# Generated by Django 4.2.1 on 2023-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='films', to='films.director'),
        ),
    ]
